name: 'Runtime checks'
description: 'Run dynamic analysis tools'

runs:
  using: "composite"
  steps:
    # --- 1. SETUP VIRTUAL DISPLAY ---
    - name: Install Virtual Display Dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y xvfb

    # --- 2. SANITIZERS (Linux & macOS) ---
    - name: Sanitizers
      shell: bash
      if: matrix.runs_asan == true && runner.os != 'Windows'
      run: |
        # Grant execution permissions
        chmod +x "./${ZIP_NAME}/${EXECUTABLE_NAME}"
        
        # If Linux, wrap with xvfb. If Mac, run normally.
        if [ "$RUNNER_OS" == "Linux" ]; then
          cat "${INPUT_FILENAME}" | tr -d '\r' | xvfb-run -a "./${ZIP_NAME}/${EXECUTABLE_NAME}"
        else
          cat "${INPUT_FILENAME}" | tr -d '\r' | "./${ZIP_NAME}/${EXECUTABLE_NAME}"
        fi

    # --- 3. SANITIZERS (Windows MSVC) ---
    - name: Sanitizers (Windows MSVC)
      shell: bash
      if: matrix.cxx == 'cl' && matrix.runs_asan == true
      continue-on-error: true
      run: |
        cat "${INPUT_FILENAME}" | "./${ZIP_NAME}/${EXECUTABLE_NAME}.exe"

    # --- 4. VALGRIND (Linux) ---
    - name: Valgrind
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      run: |
        # Wrap Valgrind with the virtual display since it executes the game under the hood
        xvfb-run -a bash ./scripts/run_valgrind.sh "${ZIP_NAME}"
